qwen:
  api_key: "sk-e95d2534e97b4a969ce20cb8819ddbc6"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

liblibai:
  access_key: "fcULyLSOwdrOmGpFEohhZg"
  secret_key: "Q4tlxV4CnpCN5aFSKXwOMTO1PHFRp6rS"
  api_url: "https://openapi.liblibai.cloud/api/generate/webui/text2img"
  query_url: "https://openapi.liblibai.cloud/api/generate/webui/status"

video:
  api_url: "https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis"
  task_url: "https://dashscope.aliyuncs.com/api/v1/tasks" 